src/include/libminiasync.h

I've forgot to update public header includes in https://github.com/pmem/miniasync/pull/9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/18)

masync: fix public header includes

---

src/vdm.c

Found by coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/21)

masync: fix uninitialized variable in vdm

---

src/include/libminiasync/vdm.h
src/vdm.c

vdm_data was moved from vdm_descriptor to vdm.
vdm_descriptor stores pointers to the vdm_data init/fini functions
instead. This allows vdm implementations to manage the data that
those implementations might need for the lifetime of a mover
instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/30)

masync: move vdm_data and add init/fini funcs

---

examples/basic/basic.c
src/CMakeLists.txt
src/future.c
src/include/libminiasync/future.h
src/include/libminiasync/vdm.h
src/runtime.c
src/vdm.c

This enables futures and runtimes to support a wider
variety of different notification mechanisms for indicating
that a future is ready to be polled again.
This PR implements pollers, which can allow runtimes to use
optimized umwait/umonitor instructions when possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/15)

masync: add expanded future notifier types

---

src/include/libminiasync/vdm.h
src/include/libminiasync/vdm_threads.h

Fix for wrong includes in vdm.h and vdm_threads.h header files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/44)

masync: fix private headers inside public vdm.h header

---

examples/basic/basic.c
src/core/os_thread_windows.c
src/core/os_windows.c
src/future.c
src/windows/include/platform.h
tests/dml_vdm/dml_vdm.c
tests/dummy/dummy.c
tests/dummy_negative/dummy_negative.c
tests/memcpy_threads/memcpy_threads.c

Includes fixes for:
-  'strdup': The POSIX name for this item is deprecated warning
-  various unreferenced formal parameter warnings
-  conversion from 'int' to 'sigset_t' warning
-  'rand_s' undefined warning
-  'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 4 has type 'size_t' warning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/46)

common: fix minor warnings on Windows

---

src/core/os_thread_windows.c
src/core/ringbuf.c
src/include/libminiasync/future.h
src/windows/include/platform.h

Includes fixes for all the `padding added after data member` warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/47)

common: fix padding warnings on Windows

---

src/core/cpu.c
src/core/os_thread_windows.c
src/core/out.c
src/core/util_windows.c
src/core/valgrind_internal.h
src/windows/include/platform.h

Includes fixes for:
-  conversion from 'int' to 'WORD', possible loss of data warning
-  signed/unsigned mismatch warnings
-  'int *' differs in indirection to slightly different base types from 'unsigned int *' warning
- 'DEBUG' macro redefinition warning
- undefined macros in `valgrind_internal.h` file warnings
- undefined macros in `out.c` file warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/49)

common: fix type mismatch warnings on Windows

---

src/data_mover_threads.c
src/include/libminiasync/data_mover_threads.h

Add an array of function pointers to change memcpy used by data mover threads. I tried to write it in such way that it won't break the abstraction of vdm, so the data functions can be any function we want, but at the moment there is only memcpy and memcpy with flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/53)

masync: vdm threads add data function pointers array

---

extras/dml/data_mover_dml.c
src/core/membuf.c
src/core/membuf.h
src/data_mover_sync.c
src/data_mover_threads.c
tests/membuf/membuf_simple.c

Originally I wanted membuf to automatically detect whenever
an allocated memory buffer becomes unused. But the implementation
had a race that might have led to use-after-free in the vdm poll
implementation. The only solution to fix that problem that I came up
with required at least one compare-and-swap even in the happy path,
which might add needless performance overhead.
This patch simplifies membuf reclamation by just adding a free
operation that should be called inside of a vdm delete operation.
This avoids the race at the cost of async movers not being able
to reclaim memory prior to the user calling poll on a completed
future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

masync: simplify membuf memory reclamation

---

CMakeLists.txt
src/core/membuf.c
src/data_mover_threads.c

Enables WX and W3 flags on Windows, as well as, fixes the remaining warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/60)

common: enable -WX flag on Windows

---

src/include/libminiasync/future.h
tests/CMakeLists.txt
tests/future/test_future.c
tests/future/test_future.cmake

This patch makes it safe to poll on completed futures,
simplifying group handling of futures (e.g., in runtimes).
I've also added a new basic test and a few tiny helper APIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/61)

masync: make future safe to poll when complete

---

src/include/libminiasync/future.h
src/include/libminiasync/vdm.h

"invalid conversion from ‘void*’ to ...".
Each time future.h or vdm.h were included in a C++ build
(pmemstream's in my case) it was causing errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/69)

masync: fix C++ compiler's warnings

---

doc/data_mover_dml_new.3.md
doc/miniasync_vdm.7.md
doc/miniasync_vdm_dml.7.md
extras/dml/data_mover_dml.c
extras/dml/include/libminiasync-vdm-dml.h
extras/dml/include/libminiasync-vdm-dml/data_mover_dml.h
src/data_mover_sync.c
src/data_mover_threads.c
src/include/libminiasync/vdm.h
tests/CMakeLists.txt
tests/data_mover_dml/data_mover_dml.c
tests/vdm/test_vdm.c
tests/vdm/test_vdm.cmake

Right now the vdm_operation_future hides all operation
details behind a mover-specific data pointer. This
makes it impossible to alter the operation arguments
inside of a chained future. This patch moves all operation
data to the the externally visible vdm_operation_data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/63)

masync: make vdm operation accessible in the future

---

doc/miniasync_future.7.md
src/include/libminiasync/future.h
tests/future/test_future.c
tests/vdm/test_vdm.c

This patch adds the ability for chained entries to be
lazily initialized and introduces a new FUTURE_CHAIN_ENTRY_LAST
macro that makes it possible for chained future data structs
to contain an extra state after the last chain entry.
Based on #63
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/64)

 masync: expand chained future functionality 

---

examples/basic-async/basic-async.c
examples/basic/basic.c
extras/dml/data_mover_dml.c
src/data_mover_threads.c
tests/data_mover_dml/data_mover_dml.c
tests/future/test_future.c
tests/memcpy_threads/memcpy_threads.c
tests/memmove_sync/memmove_sync.c
tests/vdm/test_vdm.c

I noticed that some headers were redundant, so I removed them. Please correct me if any of them is necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/75)

masync: fix redundant headers

---

src/core/cpu.c
src/core/cpu.h
src/core/util.h
src/include/libminiasync/future.h
src/runtime.c
tests/cmake/ctest_helpers.cmake
tests/future/test_future.c

Fixes: https://github.com/pmem/miniasync/pull/80.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/91)

fix builds for non-x86 architectures

---

tests/vdm/test_vdm.c

tests/vdm/test_vdm.c:39:2: warning: ISO C does not allow extra ‘;’ outside of a function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/93)

a stray semicolon warning

---

utils/check-commit.sh
utils/check-commits.sh
utils/md2man/default.man
utils/src2mans.sh

along with other 'RPMA' occurences in (most likely copy-pasted) scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/99)

common: replace improper 'RPMA' in man pages with 'MINIASYNC'

---

src/include/libminiasync/future.h

This change introduces explicit casting to avoid following error:
invalid conversion from 'void*' to 'future*'.
The newest version of miniasync blocks pmemstream build.
Best regards,
Krzysztof Filipek
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/109)

Avoid casting error on C++ compilation

---

utils/check_license/check-headers.sh

It silents the following warnings:
grep: warning: * at start of expression
See: pmem/rpma@8dd612d
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/115)

common: remove unneeded '*' at start of expressions
