- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wlemkows/libuasync/4)
> common: update links in the README.md file

- .github/workflows/coverity.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wlemkows/libuasync/6)
> common: add coverity yml

- .github/workflows/coverity.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wlemkows/libuasync/7)
> common: fix coverity run

- utils/docker/images/Dockerfile.ubuntu-21.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wlemkows/libuasync/10)
> common: add wget to Ubuntu image

- src/future.c
- src/include/future.h
- src/include/mover.h
- src/include/runtime.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wlemkows/libuasync/5)
> doc: add basic header docs

- README.md
- utils/docker/images/Dockerfile.ubuntu-21.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wlemkows/libuasync/11)
> common: coverity fixes

- .github/workflows/coverity.yml
- .github/workflows/on_pull_request.yml
- CMakeLists.txt
- README.md
- examples/basic/basic.c
- src/CMakeLists.txt
- src/include/libminiasync.h
- utils/check-area.sh
- utils/check-commit.sh
- utils/docker/build.sh
- utils/docker/images/Dockerfile.fedora-34
- utils/docker/images/Dockerfile.ubuntu-21.04
- utils/docker/images/build-image.sh
- utils/docker/run-build.sh
- utils/docker/run-doc-update.sh
- utils/mans_header.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/12)
> masync: rename uasync to masync

- .github/workflows/on_pull_request.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/13)
> masync: fix repo name in on_pull_request GHA

- utils/docker/run-coverity.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/16)
> common: set appropriate env variables for coverity

- examples/basic/basic.c
- src/include/libminiasync.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/19)
> masync: fix minor include errors

- CMakeLists.txt
- README.md
- cmake/functions.cmake
- examples/CMakeLists.txt
- examples/README.md
- examples/basic/basic.c
- src/CMakeLists.txt
- tests/CMakeLists.txt
- tests/cmake/ctest_helpers.cmake
- tests/cmake/test_helpers.cmake
- tests/drd-log.supp
- tests/dummy/dummy.c
- tests/dummy/test_dummy.cmake
- tests/dummy_negative/dummy_negative.c
- tests/dummy_negative/test_dummy_negative.cmake
- tests/ex_basic/test_ex_basic.cmake
- tests/helgrind-log.supp
- utils/docker/images/Dockerfile.fedora-34
- utils/docker/images/Dockerfile.ubuntu-21.04
- utils/docker/run-build.sh
The draft of the build system for examples and tests.
**To do:**
1. _(fixed)_ I'm not sure if the test directory is set correctly, I have to look into it because the directory tree, after building tests, seems a bit off.
2. _(fixed)_ I don't think I test the example correctly, since right now I basically have two exact same binary files, one for the example and one for the test. I should probably just use the example binary, without creating another one only for the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/8)
> common: add build system for examples and tests

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/20)
> common: update coverity badge in the readme

- doc/miniasync.7.md.in
- doc/miniasync_future.3.md.in
- doc/miniasync_runtime.3.md.in
- doc/miniasync_vdm.3.md.in
This PR adds documentation skeletons with a few sample entries . Automation scripts will be added in separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/23)
> doc: add documentation skeletons

- CMakeLists.txt
- doc/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/26)
> doc: add CMakeLists file to the man pages

- .github/workflows/on_pull_request.yml
- utils/docker/images/Dockerfile.fedora-35
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/29)
> common: upgrade Dockerfile to F35

- .github/workflows/on_pull_request.yml
- CMakeLists.txt
- cmake/cmake_uninstall.cmake.in
- utils/docker/run-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/27)
> common: add uninstall target

- examples/basic/basic.c
- src/core/alloc.c
- src/core/alloc.h
- src/core/errno_freebsd.h
- src/core/fault_injection.h
- src/core/os.h
- src/core/os_posix.c
- src/core/os_thread.h
- src/core/os_thread_posix.c
- src/core/out.c
- src/core/out.h
- src/core/util.c
- src/core/util.h
- src/include/libminiasync/vdm.h
- src/vdm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/32)
> common: replace functions from stdatomic with wrappers

- CMakeLists.txt
- examples/basic/basic.c
- extras/dml/.gitignore
- extras/dml/CMakeLists.txt
- extras/dml/include/libminiasync-dml.h
- extras/dml/include/libminiasync-dml/vdm_dml.h
- extras/dml/vdm_dml.c
- src/CMakeLists.txt
- src/include/libminiasync/future.h
- src/include/libminiasync/runtime.h
- src/include/libminiasync/vdm.h
- src/vdm.c
- utils/docker/images/Dockerfile.fedora-35
- utils/docker/images/Dockerfile.ubuntu-21.04
- utils/docker/images/install-dml.sh
- utils/docker/run-build.sh
Includes https://github.com/pmem/miniasync/pull/15.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/22)
> masync: add dml mover implementation

- src/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/36)
> mminiasync: make library shared again

- doc/CMakeLists.txt
- doc/miniasync_vdm.3.md.in
- doc/miniasync_vdm_synchronous.3.md.in
- doc/miniasync_vdm_threads.3.md.in
- examples/CMakeLists.txt
- examples/basic-async/basic-async.c
- examples/basic/basic.c
- src/CMakeLists.txt
- src/core/ringbuf.c
- src/core/ringbuf.h
- src/core/sys_util.h
- src/include/libminiasync.h
- src/include/libminiasync/vdm.h
- src/include/libminiasync/vdm_threads.h
- src/runtime.c
- src/vdm.c
- src/vdm_threads.c
- tests/CMakeLists.txt
- tests/ex_basic_async/test_ex_basic_async.cmake
- tests/memcpy_threads/memcpy_threads.c
- tests/memcpy_threads/test_memcpy_threads.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/33)
> masync: pthread memcpy with FIFO queue to ringbuffer

- src/core/util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/39)
> common: fix compilation issue on release version

- doc/miniasync_vdm.3.md.in
- src/vdm.c
- src/vdm_threads.c
- tests/memcpy_threads/memcpy_threads.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/37)
> masync: fix memory leaks and coverity issues

- .github/workflows/on_pull_request.yml
- CMakeLists.txt
- src/CMakeLists.txt
- src/core/os_thread_windows.c
- src/core/os_windows.c
- src/core/pmemcompat.h
- src/core/ringbuf.c
- src/core/ringbuf.h
- src/core/util_posix.c
- src/core/util_windows.c
- src/include/libminiasync/future.h
- src/miniasync.def
- src/runtime.c
- src/windows/include/endian.h
- src/windows/include/platform.h
- src/windows/include/sys/param.h
- src/windows/include/unistd.h
- tests/CMakeLists.txt
- tests/cmake/ctest_helpers.cmake
- tests/cmake/test_helpers.cmake
- tests/dummy/test_dummy.cmake
- tests/dummy_negative/test_dummy_negative.cmake
- tests/ex_basic/test_ex_basic.cmake
- tests/ex_basic_async/test_ex_basic_async.cmake
- tests/memcpy_threads/test_memcpy_threads.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/31)
The `-WX` flag, to treat all warnings as errors on Windows, as well as fixes of those warnings, will be added in the next PR.
Includes #33
> common: add support for Windows build system

- .github/workflows/on_pull_request.yml
- src/CMakeLists.txt
- src/core/out.h
- src/core/util.h
- tests/CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/41)
> common: fix build on Windows

- doc/CMakeLists.txt
- doc/miniasync_vdm.3.md.in
- doc/miniasync_vdm_dml.3.md.in
- doc/miniasync_vdm_synchronous.3.md.in
- doc/miniasync_vdm_threads.3.md.in
- examples/CMakeLists.txt
- examples/basic/basic.c
- extras/dml/CMakeLists.txt
- src/CMakeLists.txt
- src/include/libminiasync/future.h
- src/include/libminiasync/vdm_threads.h
I started reading your docs and examples and I've encountered a few random, rather small issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/45)
> Various fixes

- examples/basic-async/basic-async.c
- examples/basic/basic.c
- src/core/membuf.c
- src/data_mover_sync.c
- src/data_mover_threads.c
- src/runtime.c
- src/vdm.c
- tests/CMakeLists.txt
- tests/memcpy_threads/memcpy_threads.c
- tests/test_helpers.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/52)
> common: fix KW/Cov issues

- examples/basic/basic.c
- extras/dml/data_mover_dml.c
- src/core/os_windows.c
- src/core/ringbuf.c
- src/data_mover_sync.c
- src/data_mover_threads.c
- src/include/libminiasync/vdm.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/55)
> common: fix nameless union/struct warning

- examples/basic-async/basic-async.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/58)
> common: fix Cov issue

- src/core/os.h
- src/core/os_posix.c
- src/core/os_windows.c
- src/core/util.h
- src/core/util_posix.c
- src/core/util_windows.c
- src/windows/include/platform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/59)
> common: rm some dead code

- src/include/libminiasync/future.h
- tests/future/test_future.c
Based on #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/62)
> masync: fix possible alignment issues in chained futures

- tests/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/68)
> tests: run examples only if they are built

- doc/data_mover_sync_get_vdm.3.md
- doc/manuals.txt
- doc/miniasync_vdm.7.md
- doc/miniasync_vdm_synchronous.7.md
- doc/vdm_memmove.3.md
- src/data_mover_sync.c
- src/include/libminiasync/vdm.h
- tests/CMakeLists.txt
- tests/memmove_sync/memmove_sync.c
- tests/memmove_sync/test_memmove_sync.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/66)
> masync: add memmove operation for synchronous data mover

- examples/basic/basic.c
Add an additional map to transform the last entry's output into chained future's output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/67)
> example: pass error code to chained future's output

- tests/membuf/membuf_simple.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/74)
> test: prevent NULL dereferention (KW issue)

- examples/basic/basic.c
- src/include/libminiasync/future.h
- src/include/libminiasync/vdm.h
- tests/future/test_future.c
- tests/vdm/test_vdm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/76)
> masync: replace {0} with proper initialisation

- doc/data_mover_sync_get_vdm.3.md
- doc/manuals.txt
- doc/miniasync_vdm.7.md
- doc/miniasync_vdm_synchronous.7.md
- doc/vdm_memcpy.3.md
- doc/vdm_memset.3.md
- src/data_mover_sync.c
- src/include/libminiasync/vdm.h
- tests/CMakeLists.txt
- tests/memset_sync/memset_sync.c
- tests/memset_sync/test_memset_sync.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/72)
> masync: add memset operation for synchronous data mover

- doc/data_mover_threads_get_vdm.3.md
- doc/miniasync_vdm_threads.7.md
- src/data_mover_threads.c
- src/include/libminiasync/data_mover_threads.h
- tests/CMakeLists.txt
- tests/memmove_threads/memmove_threads.c
- tests/memmove_threads/test_memmove_threads.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/77)
> masync: add memmove operation to the thread data mover

- doc/data_mover_threads_get_vdm.3.md
- doc/miniasync_vdm_threads.7.md
- src/data_mover_threads.c
- src/include/libminiasync/data_mover_threads.h
- tests/CMakeLists.txt
- tests/memset_threads/memset_threads.c
- tests/memset_threads/test_memset_threads.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/78)
> masync: add memset operation to the thread data mover

- src/include/libminiasync/vdm.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/81)
> masync: fix static analyzer issue

- doc/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/82)
> masync: fix installation of section 7 manpages

- tests/test_helpers.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/85)
> masync: remove duplicated whitespace

- tests/CMakeLists.txt
- tests/test_helpers.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/86)
> masync: add test_helpers.h to cstyle

- doc/data_mover_dml_get_vdm.3.md
- doc/miniasync_vdm_dml.7.md
- extras/dml/data_mover_dml.c
- tests/CMakeLists.txt
- tests/data_mover_dml_memcpy/data_mover_dml_memcpy.c
- tests/data_mover_dml_memcpy/test_data_mover_dml_memcpy.cmake
- tests/data_mover_dml_memmove/data_mover_dml_memmove.c
- tests/data_mover_dml_memmove/test_data_mover_dml_memmove.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/84)
> masync: add memmove operation for dml data mover

- doc/data_mover_dml_get_vdm.3.md
- doc/miniasync_vdm_dml.7.md
- extras/dml/CMakeLists.txt
- extras/dml/data_mover_dml.c
- tests/CMakeLists.txt
- tests/data_mover_dml_memcpy/data_mover_dml_memcpy.c
- tests/data_mover_dml_memcpy/test_data_mover_dml_memcpy.cmake
- tests/data_mover_dml_memmove/data_mover_dml_memmove.c
- tests/data_mover_dml_memmove/test_data_mover_dml_memmove.cmake
- tests/data_mover_dml_memset/data_mover_dml_memset.c
- tests/data_mover_dml_memset/test_data_mover_dml_memset.cmake
- tests/test_helpers.h
- tests/vdm_operation_future_poll/test_vdm_operation_future_poll.cmake
Depends on https://github.com/pmem/miniasync/pull/84.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/88)
> masync: add memset operation for DML data mover

- tests/memmove_sync/memmove_sync.c
- tests/memmove_threads/memmove_threads.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/89)
> common: fix KW issues

- src/CMakeLists.txt
0 for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/94)
> declare a soversion

- src/CMakeLists.txt
- src/miniasync.def
- src/miniasync.map
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/98)
> common: add map linker file

- src/core/util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/96)
> Drop failing arch-specific #ifdefs.

- doc/miniasync_future.7.md
- src/include/libminiasync/future.h
- tests/future/test_future.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/92)
> masync: add macro to check if chain entry was initialized

- examples/CMakeLists.txt
- examples/hashmap/hashmap.c
- tests/CMakeLists.txt
- tests/ex_hashmap/test_ex_hashmap.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/71)
> masync: add hashmap example

- src/core/ringbuf.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/103)
> common: use correct atomics in ringbuf

- extras/dml/data_mover_dml.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/102)
> masync: add destination_readback flag to persistent memory writes

- doc/data_mover_dml_get_vdm.3.md
- doc/manuals.txt
- doc/miniasync_vdm.7.md
- doc/miniasync_vdm_dml.7.md
- doc/vdm_flush.3.md
- doc/vdm_is_supported.3.md
- doc/vdm_memcpy.3.md
- doc/vdm_memmove.3.md
- doc/vdm_memset.3.md
- extras/dml/data_mover_dml.c
- src/data_mover_sync.c
- src/data_mover_threads.c
- src/include/libminiasync/vdm.h
- tests/CMakeLists.txt
- tests/data_mover_dml_flush/data_mover_dml_flush.c
- tests/data_mover_dml_flush/test_data_mover_dml_flush.cmake
- tests/data_mover_dml_memcpy/test_data_mover_dml_memcpy.cmake
- tests/data_mover_dml_memset/test_data_mover_dml_memset.cmake
- tests/future/test_future.cmake
- tests/memcpy_threads/test_memcpy_threads.cmake
- tests/memmove_sync/test_memmove_sync.cmake
- tests/memmove_threads/test_memmove_threads.cmake
- tests/memset_sync/test_memset_sync.cmake
- tests/memset_threads/test_memset_threads.cmake
- tests/vdm/test_vdm.cmake
- tests/vdm_operation_future_poll/test_vdm_operation_future_poll.cmake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/90)
> masync: add flush operation for DML data mover

- extras/dml/data_mover_dml.c
- src/data_mover_sync.c
- src/data_mover_threads.c
- src/include/libminiasync/future.h
- src/include/libminiasync/vdm.h
- src/runtime.c
- tests/CMakeLists.txt
- tests/future_properties/future_property_async.c
- tests/future_properties/test_future_properties.cmake
- tests/runtime_test/runtime_test.c
- tests/runtime_test/test_runtime.cmake
The documentation to these changes will be added in another PR since this one is already growing too big.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/100)
> masync: add flag indicating that future is async

- doc/miniasync_future.7.md
- doc/runtime_wait.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/105)
> doc: add async property to documentation

- doc/miniasync_future.7.md
- doc/runtime_wait.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/106)
> doc: update async property documentation

- src/core/membuf.c
- tests/membuf/membuf_simple.c
Fixes #107 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/108)
> core: fix use-after-free in membuf in mt scenarios

- src/include/libminiasync/future.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/110)
> masync: suppres unused parameters in future.h

- examples/hashmap/hashmap.c
- tests/future_properties/future_property_async.c
- tests/membuf/membuf_simple.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/miniasync/113)
> masync: fix critical KW issues
